[package]
name = "bedrock-crypto"
description = "Bedrock login chain, key agreement, stream cipher and batch compression."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]

[lints]
workspace = true
